[package]
name = "mathlab"
version = "0.3.3"
authors = ["Montasir Mirghani <contact@montasir.me>"]
edition = "2021"
description = "A Powerful Math Library for Rust"
homepage = "https://github.com/dr-montasir/mathlab"
repository = "https://github.com/dr-montasir/mathlab"
readme = "README.md"
keywords = ["Math", "Numeric", "Native_Math"]
categories = ["mathematics"]
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
